# -*- coding: utf-8 -*-
"""Desafio4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CXudfjbAThwt2ruuchK7O2YZQPK24AJo

Imports das bibliotecas usadas
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
import seaborn as sns

"""Carregando o arquivo e salvando ele em uma variável para ser analisado no Collab"""

df = pd.read_csv("MKT.csv")

"""`df.head( )`
`df.describe( )`
`df.info( )`
Para analisar estatitiscamente melhor os dados
"""

df.head()

df.describe()

df.info()

"""3 gráficos de regressão, para comparar a relação de cada plataforma com os sales"""

sns.regplot(data=df, x=df['youtube'], y=['sales'])

sns.regplot(data=df, x=df['facebook'], y=df['sales'])

sns.regplot(data=df, x=df['newspaper'], y=df['sales'])

"""Definindo o X e Y para o Machine Learning"""

X = df[['youtube', 'facebook', 'newspaper']]
y = df[['sales']]

"""Definindo a divisão do treino e teste do modelo

Definindo variável do modelo de regressão

Treinando ele com as parcelas de treino
"""

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, test_size=0.3)
lm = LinearRegression()
lm.fit(X_train, y_train)

"""Testando o modelo e printando na tela o r2 score que teve aproximadamente 92% de acurácia."""

pred = lm.predict(X_test)
r = r2_score(y_test, pred)
print(r)